# deploy.yml
name: deploy website to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 使用 node:18
      - name: use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      # build
      - name: next build
        run: |
          npm run build
        env:
          CI: true

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          CI: true
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_BEFORE: |
            ./run.sh --stop
          SCRIPT_AFTER: |
            ./run.sh --start
